mindsdb/mindsdb-status

.gitignore
integrations/test_huggingface_api.py
utils/config.py
utils/query_generator.py

Added unit tests for the HuggingFace API handler. This primarily tests the creation of a HuggingFace API ML Engine and in order to facilitate this, the `create_ml_engine_query()` method was also added to the `QueryGenerator` class.

Unit Test for the HuggingFace API Integration

---

integrations/test_databricks.py
requirements.txt
utils/config.py

Added unit tests for the Databricks handler. This primary tests creation of a new Databricks data source using the `CREATE DATABASE` statement.

Unit Test for the Databricks Integration

---

integrations/test_google_sheets.py
utils/config.py

Added unit tests for the Google Sheets handler. This primary tests creation of a new Google Sheets data source using the `CREATE DATABASE` statement.

Unit Test for the Google Sheets Integration

---

integrations/test_amazon_aurora.py
utils/config.py

Added unit tests for the Amazon Aurora handler. This primarily tests the creation of new Amazon Aurora data sources for both MySQL and PostgreSQL using the CREATE DATABASE statements.

Unit Tests for the Amazon Aurora Integration

---

integrations/test_github.py
utils/config.py

Added unit tests for the Github handler. This primary tests creation of a new Github data source using the `CREATE DATABASE` statement.

Unit Tests for the GitHub Integration

---

integrations/test_apache_ignite.py
services/docker-compose.yml
utils/config_example.json
utils/query_generator.py

This PR includes the unit tests for the Apache Ignite integration and also includes a docker-compose.yml file, which allows a Docker container running Apache Ignite to be spun up. This file defines the skeleton for adding other services for the integrations that are to be tested.

Unit Tests for Apache Ignite

---

.github/workflows/test.yaml
integrations/test_youtube.py
utils/config.py
utils/config_example.json

Unit tests for `CREATE` Database using `YouTube` Integration.

[Test]: YouTube Integration

---

.github/workflows/test.yaml
integrations/applications/test_binance.py
utils/config_example.json

Successfully tested Binance Integration

Unit Tests for Binance

---

integrations/test_supabase.py
utils/config_example.json

Add supabase tests

---

integrations/ml/test_monkeylearn.py
utils/config_example.json

Added the test cases for monkeylearn ML engine

Unit tests for monkeylearn engine

---

integrations/test_couchbase.py
services/docker-compose.yml
utils/config_example.json

Create tests and add couchbase to the repo.

Couchbase Tests.

---

integrations/test_hackernews.py

Added unit tests for the Hacker News handler. This primarily tests the creation of a new Hacker News data source using the CREATE DATABASE statement.

Unit Tests for the Hacker News Integration

---

integrations/applications/test_mediawiki.py

Added unit tests for the MediaWiki handler. This primarily tests the creation of a new MediaWiki data source using the CREATE DATABASE statement.

Unit Tests for the MediaWiki Integration

---

integrations/test_cockroachdb.py
services/docker-compose.yml
utils/config_example.json

Added unit tests for the CockroachDB handler. This primarily tests the creation of a new CockroachDB data source using the CREATE DATABASE statement.

Unit Tests for the CockroachDB Integration

---

integrations/applications/test_stripe.py
utils/config_example.json

Added unit tests for the Stripe handler. This primarily tests the creation of a new Stripe data source using the CREATE DATABASE statement.

Unit Tests for the Stripe Integration

---

integrations/test_planetscale.py
utils/config_example.json

Added unit tests for the PlanetScale handler. This primarily tests the creation of a new PlanetScale data source using the CREATE DATABASE statement.

Unit Tests for the PlanetScale Integration

---

integrations/test_s3.py
utils/config_example.json

Added unit tests for the Amazon S3 handler. This primarily tests the creation of a new Amazon S3 data source using the CREATE DATABASE statement.

Unit Tests for the Amazon S3 Integration

---

integrations/test_tidb.py
utils/config_example.json

Added unit tests for the TiDB handler. This primarily tests the creation of a new Amazon TiDB data source using the CREATE DATABASE statement.

Unit Tests for the TiDB Integration 

---

.github/workflows/test.yaml
integrations/applications/test_webcrawler.py

This PRs adds initial test for the webcrawler

Add webcrawler

---

integrations/applications/test_newsapi.py
utils/config_example.json

Added unit tests for the News API handler. This primarily tests the creation of a new News API data source using the CREATE DATABASE statement.

Unit Tests for the News API Integration

---

integrations/applications/test_pypi.py

This PR adds unit tests for the PyPI handler. This primarily tests the creation of a new PyPI data source using the CREATE DATABASE statement.

Unit Tests for the PyPI Integration

---

integrations/ml/test_anthropic.py
utils/config_example.json

This PR adds unit tests for the Anthropic handler. This primarily tests the creation of a new Anthropic ML Engine using the CREATE ML ENGINE statement.

Unit Tests for the Anthropic Integration

---

integrations/vector_dbs/test_chromadb.py
utils/config_example.json

Added unit tests for the ChromaDB handler. This primarily tests the creation of a new ChromaDB data source using the `CREATE DATABASE` statement.

Unit Tests for the ChromaDB Integration

---

integrations/ml/test_popularity_recommender.py

This PR adds unit tests for the Popularity Recommender handler. This primarily tests the creation of a new Popularity Recommender ML Engine using the `CREATE ML ENGINE` statement.

CREATE ML ENGINE Unit Test for the Popularity Recommender Integration

---

.github/workflows/test.yaml
integrations/applications/test_gitlab.py

This PR adds healthchecks for GitLab

Add gitlab

---

.github/workflows/test.yaml

This PR updates the paths to some test modules that were incorrect and also adds a new command to run tests on vector DBs.

Updated Test Paths

---

integrations/test_questdb.py
services/docker-compose.yml
utils/config_example.json

This PR adds unit tests for the QuestDB handler. This primarily tests the creation of a new QuestDB data source using the CREATE DATABASE statement.

CREATE DATABASE Unit Test for the QuestDB Integration
